@echo off
REM Chrome native host wrapper script
REM Generated by Claude Code - do not edit manually
"C:\Program Files\nodejs\node.exe" "C:\Users\minho\AppData\Roaming\npm\node_modules\@anthropic-ai\claude-code\cli.js" --chrome-native-host
